### ISSUE TITLE
can not find start game button

### ISSUE THREAD

**Issue by foreversos** [tuomount/Open-Realms-of-Stars#277] opened 2019-07-24 04:01 UTC
startgame --> newgame
show game setup ui
just set some param
can't find any button to start game for go to next ui

**Comment by tuomount** [comment] 2019-07-24 14:45
There isn't next button on bottom right of the screen and cancel button on left bottom of the screen? Are you able to compile the project? This bug happened before 0.3.5 on Windows 7/10 with Java 8, but is suppose to be fixed.

Back then problem was that screen height was not enough for reserving the OS UI components. If you run the game from terminal or command line do you see this kind of text: "Adjust frame, since OS's UI component require their own space from JFrame."

Have you tried to change game resolution from options or have you enabled borderless frame?

**Comment by tuomount** [comment] 2019-07-24 14:49
Could you please tell me what operating system you are using? If you are using Linux please tell also what Desktop Envinroment you are using. This issue might be also related to java version which you are using, so please tell that too.

**Comment by foreversos** [comment] 2019-07-24 15:19
TOMOROOW I WILL REPLAY you
nOW no ENV



------------------ 原始邮件 ------------------
发件人: "Tuomo Untinen"<notifications@github.com>; 
发送时间: 2019年7月24日(星期三) 晚上10:49
收件人: "tuomount/Open-Realms-of-Stars"<Open-Realms-of-Stars@noreply.github.com>; 
抄送: "Forever"<8236410@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [tuomount/Open-Realms-of-Stars] can not find start game button(#277)




Could you please tell me what operating system you are using? If you are using Linux please tell also what Desktop Envinroment you are using. This issue might be also related to java version which you are using, so please tell that too.
 
&mdash;

**Comment by foreversos** [comment] 2019-07-25 08:51
WIN10 IDEAL2018 JAVA8 2560*1080





------------------ 原始邮件 ------------------
发件人: "Tuomo Untinen"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 晚上10:49
收件人: "tuomount/Open-Realms-of-Stars"<Open-Realms-of-Stars@noreply.github.com>;
抄送: "Forever"<8236410@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tuomount/Open-Realms-of-Stars] can not find start game button(#277)




Could you please tell me what operating system you are using? If you are using Linux please tell also what Desktop Envinroment you are using. This issue might be also related to java version which you are using, so please tell that too.

**Comment by tuomount** [comment] 2019-07-26 03:51
Try running from command line and see if you get text like: "Adjust frame, since OS's UI component require their own space from JFrame."

**Comment by foreversos** [comment] 2019-07-26 03:54
i replay email has attachmet
at here can't show it
![123](https://user-images.githubusercontent.com/3012313/61924804-f8c59200-af9b-11e9-9ba9-8931699def85.gif)
ok ,i upload

**Comment by tuomount** [comment] 2019-07-26 04:15
Okay, that confirms that JFrame adjusting does not work. Does it help if you goto options and enable bordless frame and then restart the game?

**Comment by foreversos** [comment] 2019-07-26 04:19
I do enable bordless,the problem has OK.DONE
it can work



------------------ 原始邮件 ------------------
发件人: "Tuomo Untinen"<notifications@github.com>; 
发送时间: 2019年7月26日(星期五) 中午12:15
收件人: "tuomount/Open-Realms-of-Stars"<Open-Realms-of-Stars@noreply.github.com>; 
抄送: "Forever"<8236410@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [tuomount/Open-Realms-of-Stars] can not find start game button(#277)




Okay, that confirms that JFrame adjusting does not work. Does it help if you goto options and enable bordless frame and then restart the game?
 
&mdash;

**Comment by tuomount** [comment] 2019-07-27 20:02
Could you please test would this change fix this bug without enabled borderless frame?

**Comment by tuomount** [comment] 2019-07-27 21:06
This fix broke JFrame on linux. Need to do more investigation.

**Comment by tuomount** [comment] 2019-07-27 21:17
New version available. I think I found the root cause. Root cause most likely is that contentPane is bound to size of JFrame and JFrame can be bigger than contentPane. This is because some OS add UI titlebar into JFrame size. Now content pane bounding was about 30 pixels too tall which causes that buttons at bottom were not visible.

**Comment by tuomount** [comment] 2019-08-04 19:15
This is only issue open for 0.11.0Beta release. I cannot verify myself but I assume that fixed has helped. Closing this issue.

**Closed by tuomount** 2019-08-04 19:15 UTC
Labels: Wait for verify, bug
