### ISSUE TITLE
Refactor Fleet splitting and scrapping

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#658] opened 2023-11-25 15:09 UTC
Duplicate code again, copied all over the codebase.
Also there is a bug with Fleet splitting that creates empty Fleets because of it. :smile:

**Comment by tuomount** [comment] 2023-11-29 19:59
There is now some issue with streams.

It happens in getScrapableShip() at row 1213.
This can be reproduce by running JUnit GameTest.fullGameWith8Realms.

I have no idea what is going. I tried to debug, but that stream does not seem to make any sense in debugger.

```
java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:229)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openRealmOfStars.player.fleet.Fleet.getScrapableShip(Fleet.java:1213)
	at org.openRealmOfStars.AI.Mission.MissionHandling.scrapTooManyShips(MissionHandling.java:1689)
	at org.openRealmOfStars.AI.Mission.MissionHandling.handleAttack(MissionHandling.java:1633)
	at org.openRealmOfStars.game.States.AITurnView.handleMissions(AITurnView.java:322)
	at org.openRealmOfStars.game.States.AITurnView.handleAIFleet(AITurnView.java:1671)
	at org.openRealmOfStars.game.States.AITurnView.handleAiTurn(AITurnView.java:3936)
	at org.openRealmOfStars.game.GameTest.testRunFullGameMediumWith8Realms(GameTest.java:279)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)


```

**Comment by tuomount** [comment] 2023-12-07 20:45
Seems to be working. Closing.

**Closed by tuomount** 2023-12-07 20:45 UTC
Labels: Wait for verify, Clean/Refactor
